#!/bin/sh

echo "Running golangci-lint..."
cd ./zad_04_go/main || exit 1
golangci-lint run
status=$?

if [ $status -ne 0 ]; then
    echo "golangci-lint failed. Commit aborted."
    exit 1
fi

exit 0
